### PR TITLE
Remove empty TCKVerificationSupport.java

### PR DESCRIPTION
**Pull request by rsvoboda**
Remove empty TCKVerificationSupport.java

Fixes https://github.com/reactive-streams/reactive-streams-jvm/issues/550

### CODE REVIEW

**Review by ktoso — APPROVED** [review]

**Comment by ktoso** [comment]
Thank you!

**Comment by rsvoboda** [comment]
@ktoso can you please approve the workflow to run GH Actions?

**Comment by ktoso** [comment]
In a weird twist of fate I have been removed as maintainer from this repository (tbh unsure why).

@rkuhn can you approve - this should be ok to merge AFAICS

**Comment by rkuhn** [comment]
Not sure what happened: I added you as an admin (again?). Sorry about the delay, I was traveling in parts of the world that have no Internet and then caught up with the world again.

**Comment by ktoso** [comment]
Thank you @rkuhn, nice to be back! Seems I'm allowed to do administrative tasks in OSS repos so merging things like this and releases I can handle :)

**Pull request merged**
