### PR TITLE
Moving the FlowAdapters into the core jar as a solution to #424

### PR DESCRIPTION
**Pull request by viktorklang**
Solves #424 by moving the FlowAdapters into the main jar and retires the flow-adapters artifact.

@reactive-streams/contributors Thoughts?

### CODE REVIEW

**Comment by viktorklang** [comment]
@akarnokd Everything will be compiled with source and target 1.6, but FlowAdapters will only be linked/used in the build if compiled against jdk9+ (conditional sources).

**Comment by viktorklang** [comment]
@reactive-streams/contributors Anyone?

**Comment by ktoso** [comment]
Sanity check the:

> Everything will be compiled with source and target 1.6, but FlowAdapters will only be linked in the build if compiled against jdk9+

as I'm missing where the magic that does this in our build is here. If it indeed does so, this is ready, except the minor docs addition requested above.

**Comment by ktoso** [comment]
It *has to* be done such that those are java 6 format.
We do so in Akka where most classes are JDK8 yet the Flow.* using ones are JDK9 compiled; the same *has to* be done here with regards to Java 6; which is why I'm asking if we confirmed this actually is happening now.

**Comment by ktoso** [comment]
ping @viktorklang can you confirm the result is the expected one?

**Comment by viktorklang** [comment]
Thanks @ktoso—I didn’t see the previous messages due to a broken filter in
GMail.

👍
-- 
Cheers,
√

**Comment by viktorklang** [comment]
@reactive-streams/contributors Merging!

**Comment by akarnokd** [comment]
Some users on Android + ProGuard have run into some issues due to the mixed RS jar file: https://github.com/ReactiveX/RxJava/issues/6670. This would affect any library depending on RS 1.0.3+ under similar circumstances.

Would the README.md of this repo a good place to document this case and the workarounds?

**Pull request merged**
