### PR TITLE
update ref to 1.0.0.final

### PR DESCRIPTION
**Pull request by smaldini**
WIP for #223

### CODE REVIEW

**Comment by viktorklang** [comment]
Looks good so far :)

**Comment by smaldini** [comment]
Any feedback on the grammar, I think so far so good on this side but I feel a bit dodgy on this aspect to check the related box :)

**Comment by viktorklang** [comment]
@smaldini I've done a pass, but I'd like to have more eyes on it.

**Comment by smaldini** [comment]
maybe we can start the release of the binary and checks the impls too.

**Comment by smaldini** [comment]
Right let's start the testing process, should I publish final on codehaus before merging @viktorklang ?

**Comment by viktorklang** [comment]
@smaldini I'm not sure, assuming we already validated the integrity of the bits (perhaps do a RC5-final binary comparison before pushing?) it seems like we should be able to push it to maven central.
Wdyt?

**Comment by smaldini** [comment]
I'm usually risk averse and I would just merge and push to maven.

**Comment by viktorklang** [comment]
@smaldini Check the SHA of the RC5 jars and compare to the SHA of the final jars before pushing, and I'll sleep better :)

**Comment by smaldini** [comment]
I've rarely seen 1.0.0 that works for everyone anyway, thats why there is a minor digit hey :dancer: 
But I will test SHA

**Comment by smaldini** [comment]
there's a bunch of TCK javadoc missing but well...

**Comment by viktorklang** [comment]
@smaldini documentation improvement is never done :)

**Comment by smaldini** [comment]
Strange , .asc and md5 are different from version to another.

**Comment by smaldini** [comment]
which is strange since I'm only one commit away. looking at the content

**Comment by smaldini** [comment]
right Manifest is regenerated

**Comment by viktorklang** [comment]
@smaldini Alright, if that's the only diff then let's go :)

**Comment by smaldini** [comment]
It is on its way to maven central, joyful tear.

**Comment by viktorklang** [comment]
Awesome, @reactive-streams/contributors should update to it so we can
announce shortly.

-- 
Cheers,
√

**Comment by smaldini** [comment]
http://repo1.maven.org/maven2/org/reactivestreams/reactive-streams/1.0.0.final/

**Comment by viktorklang** [comment]
@jsuereth and @rkuhn suspect that the ".final" part of the version number
may trip up version conflict resolution.
Since the ".final" serves no purpose, I propose we pull the "1.0.0.final"
and republish it as "1.0.0" while we still can. Is that OK, @smaldini?

-- 
Cheers,
√

**Comment by alkemist** [comment]
+1

**Comment by rkuhn** [comment]
@alkemist The problem would be that OSGi considers "1.0.0" < "1.0.0.RC5", how do we set a different version in the OSGi manifest, something like "1.0.0.final" is actually the right thing for OSGi.

**Comment by alkemist** [comment]
Still +1.

**Comment by rkuhn** [comment]
background on why using "1.0.0.final" for Maven is problematic: http://mojo.codehaus.org/versions-maven-plugin/version-rules.html (in short: "1.0.0.final" is interpreted as "0.0.0-1.0.0.final" and effectively only string comparison is used)

**Comment by rkuhn** [comment]
@alkemist I take it that your +1 is for the "1.0.0" maven version. In sbt I would know how to fix the OSGi version, how do we do this in gradle?

**Comment by alkemist** [comment]
FWIW, Ivy (therefore SBT) and Gradle understand that final > rc.

**Comment by benjchristensen** [comment]
I also think we should release 1.0.0 and then if OSGi is a mess release 1.0.1 as a patch release.

**Comment by alkemist** [comment]
@rkuhn what exactly do you want to do? Just use `1.0.0.final` in the OSGi manifest?

**Comment by rkuhn** [comment]
Yes, that would solve all the issues AFAICS.

**Comment by viktorklang** [comment]
Solving all issues sounds good to me

-- 
Cheers,
√

**Comment by viktorklang** [comment]
So, what's the action plan:

What specifically needs to be done?
How do we verify that it works?
Who does what?
When?

Could someone please confirm that the 1.0.0.final bits have been pulled,
STAT? @smaldini or @rkhun should have access

-- 
Cheers,
√

**Comment by viktorklang** [comment]
@rkuhn that is

-- 
Cheers,
√

**Comment by viktorklang** [comment]
>FWIW, Ivy (therefore SBT) and Gradle understand that final > rc.

@alkemist Does it understand that "final" > "RC<n>"?

**Comment by viktorklang** [comment]
I noticed that the bits are already in the release repo and not in the staging repo. I don't think we'll be able to pull them at this point. We could contact Sonatype and investigate whether they would be able to help us out. Thoughts?

**Comment by rkuhn** [comment]
To me the situation presents itself like this:

* we must release a version that compares greater to the currently highest Maven version, which surprisingly is `0.4.0` at this point (since all our other releases are `0.0.0-<qualifier>`)
* we must release a version that compares greater to the currently highest OSGi version, which is `1.0.0.final` at this point

The simples solution would be `1.0.1`, but if we don’t like that then we can release `1.0.0` for Maven with an OSGi manifest that says `1.0.0.release`. Then we don’t need to pull artifacts and we still don’t get version collisions.

Now to the actions: I can easily execute the `1.0.1` release. If we want to go the `1.0.0` route then someone else will have to provide a patch for the gradle build to make it happen.

**Comment by viktorklang** [comment]
@rkuhn

Releasing `1.0.0` with a `1.0.0.release` manifest would not address the possible confusion between "1.0.0.final" and "1.0.0" for users though. Perhaps we needn't worry if we never advertise `1.0.0.final` or if we add documentation to only use `x.y.z` artifacts.

As for Gradle instructions I think its but @alkemist should confirm:

~~~groovy
 jar {
        manifest {
            instruction "Bundle-Vendor", "Reactive Streams SIG"
            instruction "Bundle-Description", "Reactive Streams API"
            instruction "Bundle-DocURL", "http://reactive-streams.org"
            instruction "Bundle-Version", "1.0.0.release"
        }
    }
~~~

Current OSGi config: https://github.com/reactive-streams/reactive-streams-jvm/blob/master/build.gradle#L43
Docs: http://gradle.org/docs/current/userguide/osgi_plugin.html

**Comment by rkuhn** [comment]
@viktorklang I think that the best option for `1.0.0.final` now is to never mention it anywhere. Then there should be no issues that people run into in practice.

**Comment by viktorklang** [comment]
@rkuhn The version that shall not be named.

In that case, I vote for `1.0.0` with a rectified OSGi version as you proposed.

**Comment by alkemist** [comment]
@viktorklang that Gradle config should work. I'd eyeball the JAR though.

**Comment by viktorklang** [comment]
@alkemist +1 for eyeballing the jar, and also, thanks for verifying my Gradle claims :)

**Comment by viktorklang** [comment]
So, proposed action plan:

* delete the `1.0.0.final` tag in the repo
* add the fix for the OSGi version
* update the other version references to reflect `1.0.0`
* cut the bits
* inspect generated jars for correct OSGi Manifest & version
* push 

Does that sound like a plan? Any objections or suggestions?

**Comment by smaldini** [comment]
Gradle OSGI plugin was already taking care of the bundle version but yeah making explicit is not harmful.

**Comment by rkuhn** [comment]
I tried it out with Viktor’s instructions locally and this was the resulting manifest:
~~~
rk:libs rkuhn$ cat META-INF/MANIFEST.MF 
Manifest-Version: 1.0
Bundle-Description: Reactive Streams API
Export-Package: org.reactivestreams;version="1.0.0",1.0.0.release
Bundle-SymbolicName: org.reactivestreams.reactive-streams
Bundle-Version: 1.0.0,1.0.0.release
Bundle-Name: reactive-streams
Bundle-ManifestVersion: 2
Bnd-LastModified: 1424093440000
Bundle-Vendor: Reactive Streams SIG
Bundle-DocURL: http://reactive-streams.org
Created-By: 1.8.0_31 (Oracle Corporation)
Tool: Bnd-2.1.0.20130426-122213
~~~
I tried to find information about what that version string means but that syntax is not mentioned anywhere in the freely available docs (I do not have an OSGi specification handy).

**Comment by smaldini** [comment]
Yeah Grade OSGI plugin uses the version you specify :)

**Comment by alkemist** [comment]
Ah, use `instructionReplace` instead of `instruction`.

**Comment by smaldini** [comment]
we don't need that extra line

**Comment by smaldini** [comment]
Is that correct enough for another try :) ?
```
Archive:  reactive-streams-1.0.0.jar
   creating: META-INF/
  inflating: META-INF/MANIFEST.MF    
   creating: org/
   creating: org/reactivestreams/
  inflating: org/reactivestreams/Processor.class  
  inflating: org/reactivestreams/Publisher.class  
  inflating: org/reactivestreams/Subscriber.class  
  inflating: org/reactivestreams/Subscription.class  
wifi-5-214:libs smaldini$ cat META-INF/MANIFEST.MF 
Manifest-Version: 1.0
Bundle-Description: Reactive Streams API
Export-Package: org.reactivestreams;version="1.0.0"
Bundle-SymbolicName: org.reactivestreams.reactive-streams
Bundle-Version: 1.0.0
Bundle-Name: reactive-streams
Bundle-ManifestVersion: 2
Bnd-LastModified: 1430236558000
Bundle-Vendor: Reactive Streams SIG
Bundle-DocURL: http://reactive-streams.org
Created-By: 1.8.0_20 (Oracle Corporation)
Tool: Bnd-2.1.0.20130426-122213
```

**Comment by viktorklang** [comment]
@smaldini no, "Bundle-Version: 1.0.0" is wrong according to for OSGi we need something like "Bundle-Version: 1.0.0.release" (@rkuhn can confirm)

**Comment by smaldini** [comment]
Who uses OSGI again ? sorry fixing that.

**Comment by smaldini** [comment]
```
  inflating: META-INF/MANIFEST.MF    
  inflating: org/reactivestreams/Processor.class  
  inflating: org/reactivestreams/Publisher.class  
  inflating: org/reactivestreams/Subscriber.class  
  inflating: org/reactivestreams/Subscription.class  

wifi-5-214:libs smaldini$ cat META-INF/MANIFEST.MF 

Manifest-Version: 1.0
Bundle-Description: Reactive Streams API
Export-Package: org.reactivestreams;version="1.0.0.release"
Bundle-SymbolicName: org.reactivestreams.reactive-streams
Bundle-Version: 1.0.0.release
Bundle-Name: reactive-streams
Bundle-ManifestVersion: 2
Bnd-LastModified: 1430236558000
Bundle-Vendor: Reactive Streams SIG
Bundle-DocURL: http://reactive-streams.org
Created-By: 1.8.0_20 (Oracle Corporation)
Tool: Bnd-2.1.0.20130426-122213
```

**Comment by smaldini** [comment]
now ?

**Comment by viktorklang** [comment]
I'm not sure about: "Export-Package: org.reactivestreams;version="1.0.0.release""
@rkuhn?

For the record, let it be known, OSGi is an instrument for inflicting pain.

**Comment by smaldini** [comment]
I'm going to make a slide about at springio.net tomorrow I think...

**Comment by viktorklang** [comment]
@smaldini a slide about what? OSGi?

**Comment by smaldini** [comment]
Yeah :+1: who cares about specs that are actually changing something without involving operating systems type containers.

**Comment by rkuhn** [comment]
@smaldini Your latest manifest is looking good!

**Comment by viktorklang** [comment]
@rkhun Just to make sure, is "1.0.0.release" considered to be newer than "1.0.0.RC5" by OSGi? (note difference in upper/lower case)

**Comment by rkuhn** [comment]
Yes, it is, see https://osgi.org/javadoc/r4v43/core/org/osgi/framework/Version.html (it uses `String.compareTo`).

**Comment by viktorklang** [comment]
@rkuhn Thanks!

Alright, so it looks like we have a solution!

let's switch to version `1.0.0` with OSGi version being `1.0.0.release` in the repo
generate the jars
inspect the jars to make sure they are OK
publish `1.0.0`
delete the `1.0.0.final` tag from the `reactive-streams-jvm` repository

Sounds good?

**Comment by smaldini** [comment]
The tag is not here yet since the PR was not merged. Right now it can then :)

**Comment by viktorklang** [comment]
@rkuhn @smaldini @benjchristensen @alkemist and @reactive-streams/contributors in general.

I think we ought to merge this PR and publish the fixed `1.0.0` ASAP so we can get unstuck in the release process. @rkuhn, since you discovered the problem and found an appropriate fix, would you like to do the honors of cutting the release, or should our "release general" @smaldini do it?

**Comment by rkuhn** [comment]
Yes, I’ll start with the release now.

**Comment by viktorklang** [comment]
Godspeed

-- 
Cheers,
√

**Comment by smaldini** [comment]
Thanks @rkuhn! I was literally in flight from London Publisher to Barcelona Subscriber, fortunately flights are using backpressure too.

**Comment by viktorklang** [comment]
@smaldini There is back pressure for sure, the longer the flight the worse back pain...

**Pull request merged**
