### PR TITLE
Fix a typo in org.reactivestreams.example.unicast.AsyncSubscriber

### PR DESCRIPTION
**Pull request by seratch**
This pull request fixes a minor typo in a comment.

### CODE REVIEW

**Comment by ktoso** [comment]
LGTM, good catch :)

**Comment by ktoso** [comment]
Please also add yourself to the https://github.com/reactive-streams/reactive-streams-jvm/blob/master/CopyrightWaivers.txt file, since the project is under creative-commons-zero.

**Comment by seratch** [comment]
@ktoso Also updated >CopyrightWaivers.txt

**Comment by viktorklang** [comment]
@seratch Thank you!

@reactive-streams/contributors Merging this as it is for documentation in the example which is obviously a bug.

**Pull request merged**
