### PR TITLE
Fourth attempt at fixing Travis JDK6

### PR DESCRIPTION
**Pull request by viktorklang**
This is getting ridiculous

### CODE REVIEW

**Comment by viktorklang** [comment]
@reactive-streams/contributors  Trying one more time, I've commented on the TravisCI Issue. Will merge this when it passes the build. Then I'm all out of ideas.

**Comment by viktorklang** [comment]
@reactive-streams/contributors Ah, so it isn't me who is daft, after all: https://github.com/travis-ci/travis-ci/issues/5669

**Comment by ktoso** [comment]
Aha! Thanks for finding that one, awaiting resolution... hope it happens soon :<

**Comment by viktorklang** [comment]
Seems like it was fixed already and it is TravisCI's 5669 causing the problem.

**Pull request closed without merging**
