### PR TITLE
Build using JDK9 on travis

### PR DESCRIPTION
**Pull request by ktoso**
Just released gradle 4.1-milestone-1 will allow us to unblock progress on the JDK bridge.
Works locally, will proceed on making it work on travis.

Refs #294 
Unblocks https://github.com/reactive-streams/reactive-streams-jvm/pull/296
Gradle release: https://github.com/gradle/gradle/releases/tag/v4.1.0-milestone-1

### CODE REVIEW

**Comment by ktoso** [comment]
FYI, the upgrade was done using the recommended method `./gradlew wrapper --gradle-version=4.1-milestone-1`

**Comment by ktoso** [comment]
Stuck on attempting to get JDK9 on travis, gradle is ready ;<

**Comment by ktoso** [comment]
Thanks to some dedective work by @TheSnoozer ( https://github.com/ktoso/maven-git-commit-id-plugin/issues/292#issuecomment-314550652 ) I was able to get JDK9 running, now it's a question of making the build such that we have one separate project that builds only on 9, and we can prepare the bridge artifact then.

**Comment by ktoso** [comment]
See here https://travis-ci.org/reactive-streams/reactive-streams-jvm/builds/252653299?utm_source=github_status&utm_medium=notification

build__629_-_reactive-streams_reactive-streams-jvm_-_travis_ci

**Comment by akarnokd** [comment]
You may need a script entry `export GRADLE_OPTS=-Xmx1024m` to avoid the OOMKiller 137.

**Comment by ktoso** [comment]
Closing, will be done as part of the other PR introducing the adapters I think

**Pull request closed without merging**
