### PR TITLE
upgrade to Gradle 6.0.1

### PR DESCRIPTION
**Pull request by sullis**
Command: ./gradlew wrapper --gradle-version=6.0.1

### CODE REVIEW

**Comment by viktorklang** [comment]
@sullis It seems like the "osgi" plugin does not exist in this new version of Gradle. To accept this PR that issue would need to be addressed first, so that the build passes on TravisCI.

**Comment by akarnokd** [comment]
The `bnd` plugin has replaced the osgi plugin in v5+:

https://github.com/ReactiveX/RxJava/blob/3.x/build.gradle#L18

https://github.com/ReactiveX/RxJava/blob/3.x/build.gradle#L36

https://github.com/ReactiveX/RxJava/blob/3.x/build.gradle#L138-L148

**Comment by viktorklang** [comment]
@akarnokd What would we need to change? My OSGi-fu is abysmal

**Comment by akarnokd** [comment]
I'll post a PR shortly.

**Comment by viktorklang** [comment]
Perfect, thank you @akarnokd!

**Comment by akarnokd** [comment]
Posted: #473

**Comment by viktorklang** [comment]
Closing as fixed by #473, thanks for raising this @sullis!

**Pull request closed without merging**
