### PR TITLE
Update to Gradle 2.10

### PR DESCRIPTION
**Pull request by alkemist**

### CODE REVIEW

**Comment by alkemist** [comment]
That's a very odd failure on Travis. Can someone please re-run it.

**Comment by alkemist** [comment]
Ah, I see now that it's not due to the Gradle version changes as other PRs are failing with the same problem.

**Comment by viktorklang** [comment]
@alkemist Hmm, I don't even get those update notifications. That is one weird error:

~~~scala
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(__fortify_fail+0x37)[0x7fe529866e57]
/lib/x86_64-linux-gnu/libc.so.6(+0x108d50)[0x7fe529865d50]
/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64/libnet.so(Java_java_net_Inet4AddressImpl_getLocalHostName+0x1a0)[0x7fe5190b5d80]
[0x7fe51ff84790]
~~~

**Comment by viktorklang** [comment]
@alkemist Could you try to push an amended commit to this PR and see if Travis succeeds?

**Comment by viktorklang** [comment]
@alkemist I've unb0rked the TravisCI build, try pushing again?

**Comment by alkemist** [comment]
@viktorklang wouldn't it be better just to rerun it?

**Comment by viktorklang** [comment]
Indeed, I realized Ghostery was messing up the rerun butyom in the Travis
ui for me :-/

-- 
Cheers,
√

**Comment by viktorklang** [comment]
@alkemist I've rerun the test multiple times and it still fails with the hostname crash. extension not available for gradle 2.10? Ideas?

**Comment by alkemist** [comment]
No ideas sorry. I've not seen this before. Gradle is verified to work with Sun's Java 6, but we don't test on OpenJDK.

We could try bumping to Gradle 2.12. Will push that.

**Comment by alkemist** [comment]
Superseded by https://github.com/reactive-streams/reactive-streams-jvm/pull/307.

**Pull request closed without merging**
