### PR TITLE
Adds clarification to the intents section of 2.5 that the condition m…

### PR DESCRIPTION
**Pull request by viktorklang**
…ight not always be detectable.

As discussed in #410

@reactive-streams/contributors Please weigh in here. Another option is to weaken 2.5 to be a SHOULD rule, or taking a harder stance on 2.5 and encourage the use of atomics for setting the active Subscription.

### CODE REVIEW

**Comment by DougLea** [comment]
If this is weakened, something should be said about what happens if subscribers do not do this: that they may get either no or multiple signals for subsequent elements? (We do not want to just say "undefined behavior".)

**Comment by viktorklang** [comment]
@DougLea How about something like: "Failure to enforce this rule can lead to hard to diagnose errors due to erronous signalling patterns if a Subscriber instance is reused."

**Comment by viktorklang** [comment]
@DougLea This issue is akin to being able to detect ConcurrentModification in collections for instance.

**Comment by DougLea** [comment]
We could say that failure to conform may lead to violations of Publisher rule 1 (The total number of onNext´s signalled by a Publisher to a Subscriber MUST be less than or equal to the total number of elements requested by that Subscriber´s Subscription at all times.) And other rules too, but mainly this one.

And then maybe note in rationale that such violations lead to hard -to-diagnose bugs.

**Comment by viktorklang** [comment]
@DougLea That makes a lot of sense. I'll amend this PR.

**Comment by viktorklang** [comment]
@DougLea & @reactive-streams/contributors I've updated the text, let me know what you think.

**Comment by DougLea** [comment]
OK, but you could simplify:
"prevent that two, or more, separate Publishers from thinking that they can interact" =>
"prevent two or more Publishers from trying to interact"

**Comment by viktorklang** [comment]
@DougLea Incorporated your suggestion!

@reactive-streams/contributors Yay or nay?

**Comment by viktorklang** [comment]
@reactive-streams/contributors Ping. Will merge at the end of the week unless someone objects :)

**Comment by viktorklang** [comment]
@reactive-streams/contributors Merging without objection!

**Pull request merged**
