### PR TITLE
+tck #308 allow configuring "no events during N time" separately

### PR DESCRIPTION
**Pull request by viktorklang**
Supersedes #309 because TravisCI is broken

### CODE REVIEW

**Comment by ktoso** [comment]
wat!? It actually passes now... only difference being from which branch PR originates? wat?

**Comment by viktorklang** [comment]
@ktoso Yes, there were two Travis Issues, one where it failed in general, and now it only fails for forks. :S

**Comment by viktorklang** [comment]
@reactive-streams/contributors There's been ample time to review and give feedback. Merging this.

**Comment by ktoso** [comment]
> one where it failed in general, and now it only fails for forks. :S

*Whoa...!*

Thanks for handling this one.

**Pull request merged**
