### PR TITLE
=tck #279 improve completion latch error message

### PR DESCRIPTION
**Pull request by ktoso**
Minor error message improvement which should help implementers understand what actually failed if this timeout is hit. 

Refs #279

### CODE REVIEW

**Comment by viktorklang** [comment]
LGTM, thanks @ktoso!

ping @reactive-streams/contributors, wdyt? I think it'll be a great assistance for implementors.

**Comment by benjchristensen** [comment]
:+1:

**Comment by jroper** [comment]
Thanks @ktoso! Except that I ended up chucking a tonne of debug into my tests, and finding out the problem that way :)

**Comment by viktorklang** [comment]
@ktoso Saw this now, is this ready to be merged?

**Comment by ktoso** [comment]
This is ready to merge, yes. Please push the button :)

**Pull request merged**
