### PR TITLE
Clarifying that object equality is a.equals(b) in Intent for 2.12

### PR DESCRIPTION
**Pull request by viktorklang**
@reactive-streams/contributors No semantical change, only clarification that it is `a.equals(b)` which is intended.

### CODE REVIEW

**Comment by viktorklang** [comment]
@reactive-streams/contributors Seems non-controversial. Can I merge?

**Comment by akarnokd** [comment]
I think it's ... HTTP 500.

**Comment by viktorklang** [comment]
@akarnokd ? Works for me: https://github.com/reactive-streams/reactive-streams-jvm/pull/343/commits/dad18725eea22455150fb8164f8d83e403087f13

**Comment by akarnokd** [comment]
GitHub staff resolved the 500 issues.

> clarification that it is a.equals(b) which is intended

:+1:

**Comment by viktorklang** [comment]
@akarnokd :+1:

**Comment by viktorklang** [comment]
@reactive-streams/contributors Merging

**Pull request merged**
