### PR TITLE
Remove "preview" qualifier from README.

### PR DESCRIPTION
**Pull request by JakeWharton**

### CODE REVIEW

**Comment by JakeWharton** [comment]
Build failure is (unsurprisingly) unrelated to the change.

**Comment by viktorklang** [comment]
Hi @JakeWharton,
I'm terribly sorry for the delayed response here. I must've overlooked the notification.

Would you mind adding yourself to the CopyrightWaivers.txt as per https://github.com/reactive-streams/reactive-streams-jvm/blob/master/CONTRIBUTING.md ?

**Comment by JakeWharton** [comment]
@viktorklang Added!

**Comment by viktorklang** [comment]
Thanks @JakeWharton, I've fixed the build. I'm sorry for the delay, thanks for your contribution!

**Pull request merged**
